# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Haipeng Li (李海鹏)
email: leefrancoch@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  lhaippp
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
additional_links:
- title: google scholar
  icon: fab fa-google
  url: https://scholar.google.com.hk/citations?user=67R2ZoUAAAAJ&hl=zh-CN

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/venice.JPG
about_content: | # this will include new lines to allow paragraphs
  I am currently a Ph.D. student at the SICE from the University of Electronic Science and Technology of China (UESTC), supervised by [Prof. Shuaicheng Liu](http://www.liushuaicheng.org/) and [Prof. Bing Zeng](https://www.researchgate.net/profile/Bing-Zeng-4).
  I received my Master's degree at École Nationale Supérieure des Télécommunications de Bretagne, supervised by [Prof. Laurent Brisson](http://www.laurent-brisson.fr/). Before that, I got my Bachelor's degree from the University of Electronic Science and Technology of China (UESTC). 
  My research interests include image alignment, and generative model.

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title: 2023
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **GyroFlow+: Gyroscope-Guided Unsupervised Deep Homography and Optical Flow Learning**

          **Haipeng Li**, Kunming Luo, Bing Zeng, Shuaicheng Liu 

          International Journal of Computer Vision (**IJCV**)

          [[PDF](https://arxiv.org/abs/2301.10018)]
          [Code: [Pytorch](https://github.com/lhaippp/GyroFlowPlus)]
      
      - layout: left
        title:
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Supervised Homography Learning with Realistic Dataset Generation**

          Hai Jiang\*, **Haipeng Li\***, Songchen Han, Haoqiang Fan, Bing Zeng, Shuaicheng Liu 

          International Conference on Computer Vision (**ICCV**), 2023.

          [[PDF](https://arxiv.org/pdf/2307.15353.pdf)]
          [Code: [Pytorch](https://github.com/JianghaiSCU/RealSH)]
      
      - layout: left
        title:
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Semi-supervised Deep Large-baseline Homography Estimation with Progressive Equivalence Constraint**

          Hai Jiang\*, **Haipeng Li\***, Yuhang Lu, Songchen Han, Shuaicheng Liu 

          Thirty-Seventh AAAI Conference on Artificial Intelligence (**AAAI**), 2023.

          [[PDF](https://arxiv.org/abs/2212.02763)]
          [Code: [Pytorch](https://github.com/megvii-research/LBHomo)]
          [Video: [Youtube](https://www.youtube.com/watch?v=-ktR2mwq5H4), [Bilibili](https://www.bilibili.com/video/BV13Y41117K3/)]

      - layout: left
        title: 2021
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **GyroFlow: Gyroscope-Guided Unsupervised Optical Flow Learning**

          **Haipeng Li**, Kunming Luo, Shuaicheng Liu 

          International Conference on Computer Vision (**ICCV**), 2021.

          [[PDF](https://openaccess.thecvf.com/content/ICCV2021/papers/Li_GyroFlow_Gyroscope-Guided_Unsupervised_Optical_Flow_Learning_ICCV_2021_paper.pdf)]
          [Code: [Pytorch](https://github.com/lhaippp/GyroFlow-PyTorch), [MegEngine](https://github.com/MegEngine/GyroFlow)]
          [Video: [Youtube](https://www.youtube.com/watch?v=6gh40PyWdHM), [Bilibili](https://www.bilibili.com/video/BV1Tr4y127kd/)]

      - layout: left
        title: 
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **DeepOIS: Gyroscope-Guided Deep Optical Image Stabilizer Compensation**

          Shuaicheng Liu, **Haipeng Li**, Zhengning Wang, Jue Wang, Shuyuan Zhu, Bing Zeng

          IEEE Transactions on Circuits and Systems for Video Technology (**TCSVT**)
          
          [[PDF](http://www.liushuaicheng.org/CSVT/DeepOIS.pdf)]
          [Code: [Pytorch](https://github.com/lhaippp/DeepOIS)]
  
  - title: Academic Services # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title:
        # caption: 
        # sub_title: <green_mark>Accepted</green_mark>
        description: | # this will include new lines to allow paragraphs
          ## **Conferences:** CVPR 2024

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-relative-links

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
